# Generated by Django 3.1.5 on 2021-01-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foood', '0002_south_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exfd',
            name='collegename',
            field=models.CharField(choices=[('IIIT', 'IIIT Nuzvid'), ('IIIT', 'IIIT Basara'), ('IIIT', 'IIIT Ongole')], max_length=7),
        ),
    ]
